"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";

import { Button } from "@/components/ui/Button";
import { saveRecommendationPreferences } from "@/lib/recommendation-storage";
import type { AnimeFormat, ContentTone, RecommendationPreferences } from "@/types/recommendation";

const GENRES = ["Action", "Adventure", "Comedy", "Drama", "Fantasy", "Horror", "Mystery", "Psychological", "Romance", "Sci-Fi", "Slice of Life", "Sports", "Thriller"];
const FORMATS: AnimeFormat[] = ["TV", "MOVIE", "OVA", "ONA", "SPECIAL"];
const TONES: ContentTone[] = ["light-hearted", "dark", "emotional", "action-focused"];
const INITIAL_PREFERENCES: RecommendationPreferences = { favoriteGenres: [], avoidedGenres: [], formats: [], preferredLength: "any", releasePeriod: "any", minimumScore: 60, popularity: "any", tones: [] };

function toggle<T>(list: T[], value: T): T[] { return list.includes(value) ? list.filter((item) => item !== value) : [...list, value]; }
function optionClass(selected: boolean): string { return `rounded-lg border px-3 py-2 text-sm font-medium transition-colors focus-within:ring-2 focus-within:ring-indigo-400 ${selected ? "border-indigo-500 bg-indigo-500/15 text-indigo-100" : "border-slate-700 bg-slate-900 text-slate-300 hover:border-slate-500"}`; }

export function RecommendationForm() {
  const router = useRouter();
  const [step, setStep] = useState(0);
  const [preferences, setPreferences] = useState<RecommendationPreferences>(INITIAL_PREFERENCES);
  const [error, setError] = useState("");
  const steps = ["Your taste", "How you watch", "Refine results"];

  function advance() {
    if (step === 0 && preferences.favoriteGenres.length === 0) { setError("Choose at least one favourite genre to continue."); return; }
    setError("");
    setStep((current) => Math.min(current + 1, steps.length - 1));
  }
  function submit() { saveRecommendationPreferences(preferences); router.push("/recommend/results"); }

  return <section className="mx-auto max-w-3xl"><ol className="mb-8 grid grid-cols-3 gap-2" aria-label="Questionnaire progress">{steps.map((label, index) => <li key={label} className={`border-t-2 pt-2 text-xs font-medium sm:text-sm ${index <= step ? "border-indigo-400 text-indigo-200" : "border-slate-700 text-slate-500"}`}>{index + 1}. {label}</li>)}</ol><div className="rounded-2xl border border-slate-800 bg-slate-900/60 p-5 sm:p-8">
    {step === 0 && <fieldset><legend className="text-xl font-bold text-white">What do you enjoy?</legend><p className="mt-2 text-sm text-slate-400">Pick at least one favourite genre. You can also tell us what to avoid.</p><div className="mt-6"><h2 className="text-sm font-semibold text-slate-200">Favourite genres <span className="text-indigo-300">(required)</span></h2><div className="mt-3 flex flex-wrap gap-2">{GENRES.map((genre) => <label key={genre} className={optionClass(preferences.favoriteGenres.includes(genre))}><input className="sr-only" type="checkbox" checked={preferences.favoriteGenres.includes(genre)} onChange={() => setPreferences((current) => ({ ...current, favoriteGenres: toggle(current.favoriteGenres, genre) }))} />{genre}</label>)}</div></div><div className="mt-7"><h2 className="text-sm font-semibold text-slate-200">Genres to avoid <span className="font-normal text-slate-500">(optional)</span></h2><div className="mt-3 flex flex-wrap gap-2">{GENRES.map((genre) => <label key={genre} className={optionClass(preferences.avoidedGenres.includes(genre))}><input className="sr-only" type="checkbox" checked={preferences.avoidedGenres.includes(genre)} onChange={() => setPreferences((current) => ({ ...current, avoidedGenres: toggle(current.avoidedGenres, genre) }))} />{genre}</label>)}</div></div></fieldset>}
    {step === 1 && <fieldset><legend className="text-xl font-bold text-white">How do you like to watch?</legend><div className="mt-6"><h2 className="text-sm font-semibold text-slate-200">Preferred formats</h2><div className="mt-3 flex flex-wrap gap-2">{FORMATS.map((format) => <label key={format} className={optionClass(preferences.formats.includes(format))}><input className="sr-only" type="checkbox" checked={preferences.formats.includes(format)} onChange={() => setPreferences((current) => ({ ...current, formats: toggle(current.formats, format) }))} />{format}</label>)}</div></div><div className="mt-7 grid gap-6 sm:grid-cols-2"><label className="block text-sm font-semibold text-slate-200">Preferred length<select value={preferences.preferredLength} onChange={(event) => setPreferences((current) => ({ ...current, preferredLength: event.target.value as RecommendationPreferences["preferredLength"] }))} className="mt-2 block w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2.5 font-normal text-white focus:outline-none focus:ring-2 focus:ring-indigo-400"><option value="any">Any length</option><option value="short">Short (up to 13 episodes)</option><option value="medium">Medium (14–39 episodes)</option><option value="long">Long (40+ episodes)</option></select></label><label className="block text-sm font-semibold text-slate-200">Release period<select value={preferences.releasePeriod} onChange={(event) => setPreferences((current) => ({ ...current, releasePeriod: event.target.value as RecommendationPreferences["releasePeriod"] }))} className="mt-2 block w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2.5 font-normal text-white focus:outline-none focus:ring-2 focus:ring-indigo-400"><option value="any">Any period</option><option value="recent">Recent (2021 onward)</option><option value="modern">Modern (2010–2020)</option><option value="classic">Classic (before 2010)</option></select></label></div></fieldset>}
    {step === 2 && <fieldset><legend className="text-xl font-bold text-white">Refine your results</legend><label className="mt-6 block text-sm font-semibold text-slate-200" htmlFor="minimum-score">Minimum AniList score <span className="text-indigo-300">{preferences.minimumScore}%</span><input id="minimum-score" type="range" min="40" max="95" step="5" value={preferences.minimumScore} onChange={(event) => setPreferences((current) => ({ ...current, minimumScore: Number(event.target.value) }))} className="mt-3 block w-full accent-indigo-500" /></label><div className="mt-7"><h2 className="text-sm font-semibold text-slate-200">Popularity</h2><div className="mt-3 grid gap-2 sm:grid-cols-3">{(["popular", "hidden-gems", "any"] as const).map((option) => <label key={option} className={optionClass(preferences.popularity === option)}><input className="sr-only" type="radio" name="popularity" checked={preferences.popularity === option} onChange={() => setPreferences((current) => ({ ...current, popularity: option }))} />{option === "hidden-gems" ? "Hidden gems" : option === "any" ? "No preference" : "Popular picks"}</label>)}</div></div><div className="mt-7"><h2 className="text-sm font-semibold text-slate-200">Content tone <span className="font-normal text-slate-500">(optional)</span></h2><div className="mt-3 flex flex-wrap gap-2">{TONES.map((tone) => <label key={tone} className={optionClass(preferences.tones.includes(tone))}><input className="sr-only" type="checkbox" checked={preferences.tones.includes(tone)} onChange={() => setPreferences((current) => ({ ...current, tones: toggle(current.tones, tone) }))} />{tone}</label>)}</div></div></fieldset>}
    {error && <p role="alert" className="mt-5 text-sm text-red-300">{error}</p>}<div className="mt-8 flex items-center justify-between gap-3">{step > 0 ? <Button type="button" variant="outline" onClick={() => { setError(""); setStep((current) => current - 1); }}>Back</Button> : <span />}{step < steps.length - 1 ? <Button type="button" onClick={advance}>Continue</Button> : <Button type="button" onClick={submit}>See recommendations</Button>}</div>
  </div></section>;
}
