import assert from "node:assert/strict";
import test from "node:test";

import {
  DISTANT_FADE_START_DISTANCE,
  DISTANT_HIDDEN_DISTANCE,
  getCarouselCardVisualState,
  getCarouselTargetProgress,
  getReleaseVelocity,
  getVirtualCarouselSlides,
  getVisualIndicatorIndex,
  resolveGestureIntent,
  shouldSuppressCarouselClick,
} from "./hero-carousel-logic.ts";

test("distant carousel cards fade completely before becoming hidden", () => {
  assert.equal(getCarouselCardVisualState(0).opacity, 1);
  assert.equal(getCarouselCardVisualState(1).opacity, 0.52);
  assert.equal(getCarouselCardVisualState(DISTANT_FADE_START_DISTANCE).opacity, 0.52);

  const fading = getCarouselCardVisualState(1.25);
  assert.ok(fading.opacity > 0 && fading.opacity < 0.52);
  assert.equal(fading.interactive, false);

  const hidden = getCarouselCardVisualState(DISTANT_HIDDEN_DISTANCE);
  assert.equal(hidden.opacity, 0);
  assert.equal(hidden.interactive, false);
});

test("the virtual window never repeats an anime id", () => {
  const items = Array.from({ length: 4 }, (_, id) => ({ id }));
  const slides = getVirtualCarouselSlides(items, 0, 6);
  assert.equal(slides.length, items.length);
  assert.equal(new Set(slides.map(({ anime }) => anime.id)).size, items.length);
});

test("the live indicator follows motion but not a simple press", () => {
  assert.equal(getVisualIndicatorIndex(0, -1, 24, "dragging"), 23);
  assert.equal(getVisualIndicatorIndex(23, 2, 24, "settling"), 1);
  assert.equal(getVisualIndicatorIndex(5, 3, 24, "pressing"), 5);
  assert.equal(getVisualIndicatorIndex(5, 3, 24, "idle"), 5);
});

test("gesture intent remains pending until movement is both large and directional", () => {
  assert.equal(resolveGestureIntent(6, 0, 7, 1.15), "pending");
  assert.equal(resolveGestureIntent(8, 2, 7, 1.15), "horizontal");
  assert.equal(resolveGestureIntent(2, 8, 7, 1.15), "vertical");
  assert.equal(resolveGestureIntent(8, 7.5, 7, 1.15), "pending");
});

test("projected momentum supports multi-card flicks and bounded snapping", () => {
  assert.equal(getCarouselTargetProgress(-0.2, -12, 0.2, -5, 5), -3);
  assert.equal(getCarouselTargetProgress(-0.44, 0, 0.2, -5, 5), 0);
  assert.equal(getCarouselTargetProgress(-0.56, 0, 0.2, -5, 5), -1);
  assert.equal(getCarouselTargetProgress(3.8, 14, 0.2, -5, 5), 5);
});

test("release velocity uses the recent sample window and expires after a pause", () => {
  const samples = [
    { position: 10, time: 100 },
    { position: 50, time: 140 },
  ];
  assert.equal(getReleaseVelocity(samples, 150, 90), 1);
  assert.equal(getReleaseVelocity(samples, 240, 90), 0);
});

test("only a pointer click generated by a real drag is suppressed", () => {
  assert.equal(shouldSuppressCarouselClick(false, 1), false);
  assert.equal(shouldSuppressCarouselClick(true, 1), true);
  assert.equal(shouldSuppressCarouselClick(true, 0), false);
});
